server:
  port: 80

spring:
  batch:
    jdbc:
      initialize-schema: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gyumin
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: update
