server:
  port: 9999

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gyumin
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: rhkdtlrtm12@gmail.com
    password: ggciutdvqkyrmvvi
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  thymeleaf:
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        security: trace

